
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: syd-baroya-github
    token:
      secure: d17030d8db1f869da68e9c1332e035ed2c4c8ee9
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
